BaseURL: https://tempodeaprender.netlify.app/
LanguageCode: pt-BR
HasCJKLanguage: yes
Title: Escola Tempo de Aprender
theme: hugo-pacman-theme
pygmentsStyle: default
pygmentsUseClasses: yes
Author:
  Name: Prof. Carvalho
outputs:
  home:
    - RSS
    - HTML
outputFormats:
  RSS:
    baseName: feed
    mediatype: application/rss
Params:
  AuthorHomepage: https://tempodeaprender.netlify.app/
  AuthorImg: img/author.jpg
  BottomIntroduce:
  CreativeCommons: yes
  DateFormat: 2006 01 02 
  Description: ''
  Disqus:
    ShortName: ''
  Facebook: ''
  FancyBox: yes
  GitHub: ''
  GoogleAnalytics:
    ID: ''
    gtag_ID: ''
  Imglogo: img/logo.svg
  LinkIn: ''
  MathJax: no
  MonthFormat: 2006 01 
  Strings:
    Archive: Arquivo
    Categories: Categorias 
    HideSideBar: 隐藏侧边栏
    PageNotFound: 你访问的页面不存在
    Rss: RSS 
    Search: Pesquisar
    ShowSideBar: 显示侧边栏
    TableOfContents: 文章目录
    TagCloud: 标签云
    Tags: 标签
  Subtitle: Aqui, aprender é divertido!
  Twitter: ''
  Weibo: ''
  WeiboID: 123
Menu:
  Main:
    - Name: Página inicial
      URL: /
      Weight: 1
    - Name: Sobre a escola 
      URL: /about
      Weight: 2
